version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
      image: mysql:5.7
      container_name: symdb
      restart: unless-stopped
      tty: true
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      expose:
        - "3306"
      environment:
        MYSQL_DATABASE: ""
        MYSQL_PASSWORD: ""
        MYSQL_ROOT_PASSWORD: ""
        SERVICE_TAG: dev
        SERVICE_NAME: symdb
      volumes:
        - ./mysql:/var/lib/mysql
  
  php:
    build:
      context: .
      dockerfile: ./php/symfony.dockerfile
    container_name: symfony
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    tty: true  
    depends_on:
      - database

  # Have Composer on standby for called upon commands to execute without installing Locally
  composer:
    image: composer:2.0.4
    container_name: symfony-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php